# Generated by Django 2.0.1 on 2018-02-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='py_element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('py_name', models.CharField(max_length=50, unique=True)),
                ('py_createddatetime', models.DateTimeField()),
                ('py_updatedatetime', models.DateTimeField()),
                ('py_stream', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
