# Generated by Django 2.0.1 on 2018-02-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='py_element',
            name='py_type',
            field=models.CharField(default='Section', max_length=50),
            preserve_default=False,
        ),
    ]
