# Generated by Django 2.0.1 on 2018-02-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MM', '0002_py_element_py_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPM_element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MPM_name', models.CharField(max_length=50, unique=True)),
                ('MPM_createddatetime', models.DateTimeField()),
                ('MPM_updatedatetime', models.DateTimeField()),
                ('MPM_stream', models.TextField(blank=True, null=True)),
                ('MPM_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='py_element',
        ),
    ]
